config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root to: 'sessions#new'
  # resources :articles

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	# attr_accessible :email, :password, :password_confirmation

	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

private

def current_user
	@current_user ||=User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

def authorize
	redirect_to login_url, alert: "Not authorized" if current_user.nil?
end


before_filter :require_login

  def require_login
    unless current_user
      redirect_to root_url
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
      redirect_to user, notice: "Logged in!"
  	else
  		flash.now.alert = "Email or passord is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end


	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end


	def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>crewHR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- 	<div id="container">
		<div id="user_header">
			<% if current_user %>
				Logged in as <%= current_user.email %>
				<%= link_to "Log Out", logout_path %>
			<% else %>
				<%= link_to "Sign Up", signup_path %> or
				<%= link_to "Log In", login_path %>
			<% end %>	
		</div> -->

<!-- 		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %> -->

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<% provide(:title, "") %>
<html>
<!--   <head>
  </head> -->
  <body>
	<div class="navbar navbar-static-top masthead navbar-top " role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-nav">
<!-- 					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span> -->
					<img src="http://www.defensivecarry.com/customavatars/avatar21080_1.gif" class="img-circle special-img">
				</button>
<!-- 				<a class="navbar-brand" href="#">HRxpress</a> -->
					<p id="logo">crew<span><b>HR</b></span></p>
			</div>
			<div class="collapse navbar-collapse navbar-ex1-collapse" id="top-nav">
				<ul class="nav navbar-nav navbar-right">
              <li><%= link_to '<i class="fa fa-sign-out" style="font-size: 20px;"></i> Logout'.html_safe, logout_path %></li>
					<img src="http://www.defensivecarry.com/customavatars/avatar21080_1.gif" class="img-circle special-img">

					<!-- <li class="active"><a href="#"><i class="fa fa-sign-out"></i>Logout</a></li> -->
<!--                     <li>
                     <%= link_to "<i class='fa fa-sign-out' style='font-size: 20px;'></i><span class='link-text'>&nbsp; Logout</span>".html_safe, logout_path %>
                    </li> -->
          
<!--           <img src="http://www.defensivecarry.com/customavatars/avatar21080_1.gif" class="img-circle special-img"> -->
			</div>
		</div>
	</div>	





<!-- Sidebar -->
<div id="sidebar" role="navigation">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


    <div id="sidebar-nav">
                <ul class="nav nav-stacked">

                    <li><a href="#"> <i class="fa fa-home" style="font-size: 20px;"></i><span class="link-text">&nbsp; &nbsp; HOME</a></li>
                    <li><a href="#"> <i class="fa fa-star" style="font-size: 20px;"></i><span class="link-text">&nbsp; &nbsp; MY PROFILE</a></li>
                    <li><a href="#"> <i class="fa fa-users" style="font-size: 20px;"></i><span class="link-text">&nbsp; &nbsp; MY TEAM</a></li>
                    <li><a href="#"> <i class="fa fa-sitemap" style="font-size: 20px;"></i><span class="link-text">&nbsp; &nbsp; DIRECTORY</a></li>
<!--                     <li><a href="#"> <i class="fa fa-sign-out" style="font-size: 20px;"></i><span class="link-text">&nbsp; &nbsp; LOG OUT</a></li> -->
                    
<!--                      <%= link_to "<i class='fa fa-sign-out' style='font-size: 20px;'></i><span class='link-text'>&nbsp; &nbsp; LOG OUT</span>".html_safe, logout_path %> -->

                </ul>
    </div>
</div>
<!-- Sidebar End -->



  </body>
</html>